# Generated by Django 3.1.1 on 2020-10-25 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fam', '0002_application'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Application',
        ),
    ]
