# Generated by Django 3.1.1 on 2020-10-26 03:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fam', '0005_auto_20201026_0839'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='Status',
            new_name='status',
        ),
    ]
