# Generated by Django 3.1.1 on 2020-10-26 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fam', '0006_auto_20201026_0854'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='status',
            new_name='Status',
        ),
    ]
